In [2]:
import numpy as np
from numpy import ndarray

In [ ]:
board: ndarray[int, ...] = np.zeros((4,4), dtype=int)

In [3]:
temp = np.ones((2,2))
print(temp)

[[1. 1.]
 [1. 1.]]


In [5]:
temp == 1

array([[ True,  True],
       [ True,  True]])

In [11]:
temp_where = np.where(temp == 1)
print(temp_where)
print(type(temp_where))

(array([0, 0, 1, 1]), array([0, 1, 0, 1]))
<class 'tuple'>


In [12]:
random_index = np.random.choice(temp_where[0].size)
row = temp_where[0][random_index]
col = temp_where[1][random_index]
temp[row, col] = 9
print(temp)

[[1. 1.]
 [9. 1.]]


In [19]:
temp[(1, 1)] = 2

In [123]:
print(temp)

[[1. 1.]
 [9. 2.]]


In [131]:
print(np.argwhere(temp == 1))
print(np.argwhere(temp == 1).shape)
print(np.random.choice(np.argwhere(temp == 1).shape[0]))

[[0 0]
 [0 1]]
(2, 2)
1


In [126]:
print(np.where(temp == 1))
print(list(zip(*np.where(temp == 1))))

(array([0, 0]), array([0, 1]))
[(0, 0), (0, 1)]


In [106]:
def has_open_space(board: ndarray[int, ...]) ->bool:
    return np.any(board == 0)

In [105]:
def is_valid_move(board: ndarray[int, ...], direction: int) -> bool:
    new_matrix, _ = make_move(board, 0, direction)
    return not np.array_equal(new_matrix, board)

In [122]:
def has_valid_move(board: ndarray[int, ...]) -> bool:
    # return is_valid_move(board, 0) or is_valid_move(board, 1) or is_valid_move(board, 2) or is_valid_move(board, 3)
    return any(is_valid_move(board, direction) for direction in range(4))

In [94]:
def add_value(board: ndarray[int, ...])-> ndarray[int, ...]:
    #make a list of all the empty spaces in the
    empty_spaces = list(zip(np.where(board == 0)[0], np.where(board == 0)[1]))
    # empty_spaces = np.argwhere(board == 0)
    random_index = np.random.choice(len(empty_spaces))
    new_board = board.copy()
    new_board[empty_spaces[random_index]] = np.random.choice([2,4], p=[2/3, 1/3])
    return new_board

In [91]:
def make_move(board: ndarray[int, ...], current_score: int, direction: int)-> tuple[ndarray[int, ...], int]:
    # 0: up, 1: right, 2: down, 3: left
    new_board = np.copy(board)
    new_board = np.rot90(new_board, k=direction)
    shifted_board = shift(new_board)
    joined_board, score_change = join(shifted_board)
    return_board = np.rot90(joined_board, k=(4-direction))
    return return_board, current_score + score_change


In [92]:
def shift(board: ndarray[int, ...]) -> ndarray[int, ...]:
    new_board = np.copy(board)
    for column in range(board.shape[1]):
        top_row = 0 #stores the row of the highest zero element
        for row in range(board.shape[0]):
            if new_board[row, column] != 0:
                new_board[(top_row, row), (column, column)] = new_board[(row, top_row), (column, column)]
                top_row += 1
    return new_board

In [93]:
def join(board: ndarray[int, ...]) -> tuple[ndarray[int, ...], int]:
    new_board = np.copy(board)
    score_change = 0
    for column in range(board.shape[1]):
        for row in range(board.shape[0] - 1):
            if new_board[row, column] == new_board[row + 1, column] and new_board[row, column] != 0:
                new_board[row, column] += new_board[row + 1, column]
                score_change += new_board[row, column]
                new_board[row + 1, column] = 0
                new_board[(row + 1):, column] = np.roll(new_board[(row + 1):, column], -1)
    return new_board, score_change


In [134]:
moves = {0: "up", 1: "right", 2: "down", 3: "left"}


board = np.zeros((4,4), dtype=int)
board = add_value(board)
score = 0
print(board, f"\nscore: {score}\n")
while has_valid_move(board):
    move = np.random.choice(4, p=[.4, .4, .1, .1])
    while not is_valid_move(board, move):
        move = np.random.choice(4, p=[.4, .4, .1, .1])
    print("chose move: ", moves[move])
    board, score = make_move(board, score, move)
    board = add_value(board)
    print(board, f"\nscore: {score}\n")

[[0 0 4 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 
score: 0

chose move:  right
[[0 0 0 4]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 4]] 
score: 0

chose move:  up
[[0 0 0 8]
 [0 0 4 0]
 [0 0 0 0]
 [0 0 0 0]] 
score: 8

chose move:  up
[[0 0 4 8]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]] 
score: 8

chose move:  up
[[0 2 4 8]
 [0 0 0 0]
 [2 0 0 0]
 [0 0 0 0]] 
score: 8

chose move:  up
[[2 2 4 8]
 [0 4 0 0]
 [0 0 0 0]
 [0 0 0 0]] 
score: 8

chose move:  right
[[0 4 4 8]
 [0 0 0 4]
 [0 0 0 0]
 [0 4 0 0]] 
score: 12

chose move:  up
[[0 8 4 8]
 [0 0 0 4]
 [0 0 0 0]
 [0 0 0 4]] 
score: 20

chose move:  up
[[0 8 4 8]
 [0 0 0 8]
 [0 0 0 4]
 [0 0 0 0]] 
score: 28

chose move:  left
[[8 4 8 0]
 [8 0 0 0]
 [4 0 0 0]
 [0 0 0 4]] 
score: 28

chose move:  right
[[0 8 4 8]
 [0 0 0 8]
 [4 0 0 4]
 [0 0 0 4]] 
score: 28

chose move:  up
[[ 4  8  4 16]
 [ 0  0  0  8]
 [ 0  2  0  0]
 [ 0  0  0  0]] 
score: 52

chose move:  up
[[ 4  8  4 16]
 [ 0  2  0  8]
 [ 0  2  0  0]
 [ 0  0  0  0]] 
score: 52

chose move:  left
[[ 4  8  4 1

In [43]:
count_up = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print(count_up)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [37]:
count_up[0,3]

4

In [44]:
count_up[(0,3), (0,1)] = count_up[(3,0), (1,0)]     #think rows then columns
print(count_up)

[[14  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13  1 15 16]]


In [34]:
rotated_once = np.rot90(count_up, k=1)
print(rotated_once)

[[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]


In [36]:
print(rotated_once.shape)

(4, 4)


In [35]:
rotated_zero = np.rot90(count_up, k=0)
print(rotated_zero)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [119]:
valid_test_board = np.array([[2, 4, 2, 4],
                             [4, 2, 4, 2],
                             [2, 4, 2, 4],
                             [4, 2, 4, 2]], dtype=int)

In [120]:
print(is_valid_move(valid_test_board, 3))
print(has_valid_move(valid_test_board))

False
False


In [132]:
test_board = np.array([[2, 2, 0, 2],
                       [0, 0, 2, 2],
                       [0, 2, 4, 4],
                       [0, 0, 4, 4]], dtype=int)
print(test_board)

[[2 2 0 2]
 [0 0 2 2]
 [0 2 4 4]
 [0 0 4 4]]


In [133]:
other_test_board = np.copy(test_board)
for column in range(test_board.shape[1]):
        nonzero_rows = np.nonzero(board[:, column])[0]
        other_test_board[nonzero_rows, column] = other_test_board[nonzero_rows[np.arange(len(nonzero_rows)) != nonzero_rows]] # shift non-zero elements to top
        board[nonzero_rows[-1] + 1:, column] = 0 # set remaining elements to zero
print(other_test_board)

ValueError: shape mismatch: value array of shape (0,4) could not be broadcast to indexing result of shape (4,)

In [90]:
shifted = shift(test_board)
print(shifted)
print("\n", join(shifted))

[[2 2 2 2]
 [0 2 4 2]
 [0 0 4 4]
 [0 0 0 4]]

 (array([[2, 4, 2, 4],
       [0, 0, 8, 8],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), 24)


In [70]:
new_test_board = np.copy(test_board)
new_test_board[:, 3] = np.roll(new_test_board[:, 3], -1)

In [71]:
print(new_test_board)

[[2 2 0 2]
 [0 0 0 0]
 [0 2 0 4]
 [0 0 4 0]]


In [60]:
print(shift(test_board))

[[2 2 4 2]
 [0 2 0 4]
 [0 0 0 0]
 [0 0 0 0]]
